Produkcja
KWZP/Projekt pull request #14
Opened 2018-04-26 13:57 UTC by elabrodecka

Dodanie formularzy ewidencji maszyn i narzedzi, poprawki grafiki i dodanie danych

2018-04-26 14:17 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormEwidencja.cs
> +            foreach (Control control in this.panelNarzedzia.Controls)
pętla która nic nie robi, do usuniecia

2018-04-26 14:17 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormEwidencja.cs
> +            this.ZapiszM.Text = "Zapisz";
zmienic nazwe przycisku

2018-04-26 14:17 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormEwidencja.cs
> +        private void panelMaszyny_Paint(object sender, PaintEventArgs e)
puste funkcje które nic nie robią, do usunięcia

2018-04-26 14:17 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormEwidencja.cs
> +            foreach (Control control in this.panelMaszyny.Controls)
jw

2018-04-26 14:17 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormGabaryty.cs
> +        private void lblTryb_Click(object sender, EventArgs e)
pusta funkcja, do usuniecia

2018-04-26 14:17 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormObciazenie.cs
> +        private void GridObciazenie_CellContentClick(object sender, DataGridViewCellEventArgs e)
jw

2018-04-30 09:15 UTC, rudnickirobert requested changes

2018-04-30 09:15 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormEwidencja.cs
> +            this.ZapiszM.Text = "Zapisz";
nazwa przycisku nadal nie jest zmieniona...

2018-04-30 09:15 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormEwidencja.cs
> +            textBox5.Clear();
proszę nazwać textBoxy adekwatnie do ich funkcji

2018-04-30 09:15 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormEwidencja.cs
> +        private void panelNarzedzia_Paint(object sender, PaintEventArgs e)
puste funkcje do usunięcia

2018-04-30 09:15 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormEwidencja.cs
> +        private void textBox10_TextChanged(object sender, EventArgs e)
jw

2018-04-30 09:15 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormWykorzystaneMaszyny.cs
> +        private void GridWykorzystaneMaszyny_CellContentClick(object sender, DataGridViewCellEventArgs e)
znowu puste funkcje

2018-04-30 09:15 UTC, rudnickirobert commented on PROJEKTapp/PROJEKTapp/Forms_Produkcja/FormZmiana_Maszyny.cs
> +        private void label6_Click(object sender, EventArgs e)
puste funkcje + nazewnictwo komponentów

2018-05-07 17:52 UTC, rudnickirobert commented
@DamianSzczesniak @elabrodecka dlaczego tutaj się nic nie dzieje?

2018-05-07 18:23 UTC, KamilRajkowski commented
Nic tu się nie dzieje ponieważ większość z nas wyjeżdżała w ciągu ostatniego tygodnia. Niedługo powinny zostać dodane działające formularze z ewidencją maszyn i narzędzi podobnie jak to wygląda z pracownikami oraz poprawki estetyczne jak te new entities czy puste funkcjie. Niestety z mojej strony pojawił się większy problem, który bez skutecznie próbowałem rozwiązać najpierw sam, a później z pomocą innych kierowników polegający na tym, że po z pullowaniu ostatnich zmian (później nawet po klonowaniu repozytorium z dowolnego pkt) visual wyświetla błąd o braku powiązań między tabelami, które w sql serverze istnieją i działają.

2018-05-07 20:31 UTC, mateuszkalisz commented
Puste funkcje są pousuwane, problem mamy z tym, że w ewidencji maszyn i narzędzi podczas zapisywania wywala błąd:
![image](https://user-images.githubusercontent.com/38287804/39723491-4d537d50-5246-11e8-9785-4e7bb4bbf327.png)

2018-05-08 06:30 UTC, rudnickirobert commented
@mateuszkalisz wyglada na to jakby db było nullem (nie zainicjalizowane), która to klasa?

2018-05-08 11:43 UTC, rudnickirobert commented
@mateuszkalisz nie widzę tego pliku w kodzie więc nie mogę pomóc- proszę o wcommitowanie

2018-05-08 12:22 UTC, mateuszkalisz commented
Mirka commit naprawił ta zmianę - z pomocą Damiana rozwiązaliśmy wcześniej opisywany problem

2018-05-08 22:16 UTC, DamianSzczesniak commented
Merge może iść automatycznie, Branch aktualny z kierownikiem.

2018-05-09 05:46 UTC, rudnickirobert approved these changes

2018-05-09 10:14 UTC, merged